Task2
itechart-mogilev-lab/lipenko pull request #2
Opened 2019-01-31 14:28 UTC by randomdotcom

2019-01-31 14:29 UTC, Maksim-Lipenka commented
https://randomdotcom.github.io/task2/

2019-01-31 21:00 UTC, anastasiatol requested changes
Визуально оч хорошо. 
![image](https://user-images.githubusercontent.com/30156652/52084885-2107a180-25b4-11e9-8bbf-4093e39c0016.png)
Можешь разве что серую полосочку над меню убрать (когда узкий экран)

header-title, logo, slogan -- не надо так мелко делить на блоки. эти три можно в один объединить. Блок визуально отдельный компонент

nav-menu и nav-menu-list -- тоже в один, возможно еще где то, пересмотри



Много где ты блоки позиционируешь паддингами (особенно в хедере), изменяя внешнюю геометрию блока. Потом если будем переиспользовать, нам это может помешать. 


.search {

padding-right: 5vw;

}

лучше через header-top-right-side__search



class="header__bottom header-bottom", class="article__content article-content", class='sidebar__content sidebar-content'

Ты много где так задавал, это когда блок вкладывал в блок? Обычно блок1__блок2, так же как клок__элемент. На header-bottom и др.,  нету свойств, не надо классы задавать где они не нужны



.sidebar position: absolute не надо блоку задавать позиционирование даже  в медиазапросе. 



sidebar-content__entries sidebar-entries, sidebar-content__categories sidebar-categories -- стили одинаковые

2019-02-01 08:41 UTC, randomdotcom commented
> class="header__bottom header-bottom", class="article__content article-content", class='sidebar__content sidebar-content'
> 
> Ты много где так задавал, это когда блок вкладывал в блок? Обычно блок1__блок2, так же как клок__элемент. На header-bottom и др., нету свойств, не надо классы задавать где они не нужны

На div повесил элемент от родительского блока + новый блок, вроде же так делается?

![image](https://user-images.githubusercontent.com/43496357/52111958-3d3c2a80-2616-11e9-8301-2955215ec0bc.png)

2019-02-01 08:51 UTC, anastasiatol commented
но блоку дается название как в элементе 
class = header__bottom bottom
или
class = header__header-bottom header-bottom

И не выделяй лишние блоки, блок это то, что мы можем переиспользовать

2019-02-01 09:39 UTC, randomdotcom commented
https://randomdotcom.github.io/lipenko/task2 new github page

2019-02-03 11:52 UTC, anastasiatol commented on task2/css/sidebar/sidebar.css
> +.sidebar-categories, .sidebar-entries {
даже 2 класса не надо задавать, придумываешь какое нибудь более общее название sidebar-list, например

2019-02-03 11:54 UTC, anastasiatol commented on task2/css/sidebar/media.css
> +    .sidebar .content {
sidebar__content {...}

2019-02-03 11:56 UTC, anastasiatol commented on task2/css/header/header.css
>  .header-title {
позиционирвание через паддинги

2019-02-03 12:01 UTC, anastasiatol commented on task2/css/sidebar/media.css
> +        position: absolute;
.sidebar position: absolute не надо блоку задавать позиционирование даже в медиазапросе.

2019-02-03 12:07 UTC, anastasiatol commented on task2/css/article/article.css
> +.article__content.content {
.article__content{...}

2019-02-03 12:08 UTC, anastasiatol commented on task2/css/article/media.css
> +    .article__content.content {
.article__content{...}

2019-02-03 12:09 UTC, anastasiatol approved these changes
Иконка и description не забывай

2019-02-03 12:10 UTC, merged